# Generated by Django 4.1.4 on 2022-12-13 13:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_fullname', models.CharField(max_length=255)),
                ('consumer_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=project.utils.datetime_now, editable=False)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('expired', 'Просрочен'), ('deleted', 'Не активный')], default='active', max_length=100)),
                ('deposit', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('cashless', 'Безналичные'), ('barter', 'Бартер')], max_length=50)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('term', models.CharField(choices=[('hours', 'Час'), ('days', 'День'), ('weeks', 'Неделя'), ('months fix', 'Месяц Fix'), ('months flex', 'Месяц Flex')], max_length=50)),
                ('time_type', models.CharField(choices=[('nighttime', 'Ночь'), ('daytime', 'День'), ('day', 'Сутки'), ('anytime', 'Любое время')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_fullname', models.CharField(max_length=255)),
                ('consumer_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('place_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=project.utils.datetime_now, editable=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.TextField()),
                ('created_at', models.DateTimeField(default=project.utils.datetime_now, editable=False)),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FromBookedPlaceToResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=project.utils.datetime_now, editable=False)),
                ('booked_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookedplace')),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resident.resident')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=project.utils.datetime_now, editable=False)),
                ('booked_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookedplace')),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingrequest')),
            ],
        ),
    ]
