# Generated by Django 3.2.7 on 2023-10-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20231013_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedplace',
            name='window',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
