# Generated by Django 4.1.4 on 2023-03-08 16:15

from django.db import migrations, models
import project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=project.utils.datetime_now, editable=False)),
                ('admin_fullname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('action_text', models.TextField(blank=True, default='')),
            ],
        ),
    ]
